---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.10
  - name: ubuntu-17.10
  - name: ubuntu-18.04
  - name: debian-8.10
  - name: debian-9.4
  - name: centos-6.9
  - name: centos-7.4
  - name: fedora-27
  - name: fedora-28

suites:
  - name: default
    run_list:
      - recipe[limits_test_cookbook]
    provisioner:
      client_rb:
        node_name: 'limits-test-node'
